### ISSUE TITLE
Is It possible to make it work with php version?

### ISSUE THREAD

**Issue by RodolVelasco** [PUGX/shortid-doctrine-bundle#2]
Please can you make it compatible with php version 5.6 or more.

**Comment by garak** [comment]
Did you find something in this bundle incompatible with php 5.6?

**Comment by RodolVelasco** [comment]
This is my log:

![image](https://cloud.githubusercontent.com/assets/1563191/26435627/d61a0e78-40cd-11e7-9532-542d387a65ae.png)

**Comment by garak** [comment]
As you can see, this doesn't depend on this bundle.
Please open an issue on pugx/shortid-php

**Comment by RodolVelasco** [comment]
Can I install a version of this bundle being compatible with SF2.8 or SF.3.* but at the same time compatible with pugx-short-id for php version 5.6.*? If there's a way, what's the way to do it?

**Comment by garak** [comment]
Try requiring `^0.1` of this bundle, it should require old (and compatible) versions.
Keep in mind, anyway, that such old versions are unsupported. I strongly recommend you to upgrade to php 7 as soon as you can.
