### ISSUE TITLE
Easy Read should be configureable

### ISSUE THREAD

**Issue by c33s** [PUGX/shortid-doctrine-bundle#6]
https://github.com/PUGX/shortid-php#more-readable-strings

**Comment by garak** [comment]
This is only affecting auto-generated Shortids, but anyway I agree that a configurable option makes sense.
Can you propose a PR?

**Comment by c33s** [comment]
would love to do so but sorry currently its not possible. to much workload :(

i dropped the bundle and only work directly in the constructor with `pugx/short-id` now.

**Comment by garak** [comment]
It was fixed in 751cc0534cd2a22c55f4793f3be38ab88574ce2d
